---
- name: Template out cal Service
  ansible.builtin.template:
    src: cal.service.j2
    dest: "/etc/systemd/system/cal.service"
    force: true
    mode: '0644'  # Ansible-Lint hates when this isn't set

- name: Add overwrite_certs.sh
  ansible.builtin.template:
    src: overwrite_certs.sh.j2
    dest: "{{ cal_dir }}/overwrite_certs.sh"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set
    owner: "{{ cal_service_user }}"
    group: "{{ cal_service_user }}"

- name: Copy initial cert to appropriate directory
  ansible.builtin.copy:
    src: "{{ cal_inital_cert_location }}/{{ cal_external_domain }}.crt"
    dest: "{{ cal_certificate_path }}"
    remote_src: true
    force: true
    owner: "{{ cal_service_user }}"
    group: "{{ cal_service_user }}"
    mode: "0700"

- name: Copy initial key to appropriate directory
  ansible.builtin.copy:
    src: "{{ cal_inital_cert_location }}/{{ cal_external_domain }}.key"
    dest: "{{ cal_key_path }}"
    remote_src: true
    force: true
    owner: "{{ cal_service_user }}"
    group: "{{ cal_service_user }}"
    mode: "0700"

- name: Make override directory
  ansible.builtin.file:
    path: "{{ cal_cert_renewer_path }}"
    state: directory
    mode: '0755'

- name: Deploy cal override
  ansible.builtin.template:
    src: cert-renewer.cal.override.j2
    dest: "{{ cert_renewer_path }}/override.conf"
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set

- name: Do post configuration activities for cal
  become_user: "{{ cal_service_user }}"
  ansible.builtin.command:
    cmd: "{{ cal_post_config_command }}"
    chdir: "{{ cal_dir }}"
  changed_when: false

- name: Ensure cert-renewer@bitwarden.timer is started
  ansible.builtin.service:
    name: "{{ cal_cert_timer }}"
    state: started
    enabled: true

- name: Ensure cal is restarted
  ansible.builtin.service:
    name: "{{ cal_name }}"
    state: restarted
    enabled: true
